services:
  cinect:
    build:
        context: .
        dockerfile: docker/php/Dockerfile
    container_name: cinect_app
    restart: unless-stopped
    volumes:
      - .:/var/www
    environment:
      DB_HOST: mysql-iliasvilux.alwaysdata.net
      DB_PORT: 3306
      DB_DATABASE: iliasvilux_cinect
      DB_USERNAME: 394036
      DB_PASSWORD: devVilux2025
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - cinect
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
